mam:
  auto_purchase:
    upload: false
    vip: false
    wedge: false
  buffer: 52000
  dont_spend_below: 50000
  mam_id: ''
  min_points: 55000
  session_type: ip
  wedge_hours: 168
automation:
  refresh_minutes: 5
notifications:
  email:
    enabled: false
    events:
      cookie_updated: true
      ip_changed: true
      points_below_threshold: true
      wedge_purchase: true
    smtp:
      password: ''
      port: 587
      recipient: ''
      sender: ''
      server: ''
      username: ''
  webhooks: []
mam_ip: ''
