mam:
  auto_purchase:
    upload: false
    vip: false
    wedge: false
    millionaires_vault: false
  mam_id: ''
  min_points: 55000
  session_type: ip
  wedge_hours: 168
  # Upload Credit: 1, 2.5, 5, 20, 100
  upload_amount: 1
  # VIP Status: 4, 8, or 'max' (max me out)
  vip_weeks: 4
  # FreeLeech Wedge: 'points' or 'cheese'
  wedge_method: points
  # Millionaire's Vault automation
  millionaires_vault_amount: 2000
  # Optionally, track last donation date/pot if needed for advanced logic
automation:
  refresh_minutes: 5
notifications:
  email:
    enabled: false
    events:
      cookie_updated: true
      ip_changed: true
      points_below_threshold: true
      wedge_purchase: true
    smtp:
      password: ''
      port: 587
      recipient: ''
      sender: ''
      server: ''
      username: ''
  webhooks: []
mam_ip: ''
