automation:
  refresh_minutes: 30
mam:
  auto_purchase:
    upload: true
    vip: true
    wedge: true
  buffer: 52000
  dont_spend_below: 50000
  mam_id: #UD2MLEXA9nXZm2T3OKOLyunDKZRoAap_CTIKmMQJI2g6f_RvoL9ZZ3ejXlkNDEyBIFuyq3KglPquci7BPZTe3I
  min_points: 55000
  session_type: asn
  wedge_hours: 168
mam_ip: ''
notifications:
  email:
    enabled: false
    events:
      cookie_updated: true
      ip_changed: true
      points_below_threshold: true
      wedge_purchase: true
    smtp:
      password: ''
      port: 587
      recipient: ''
      sender: ''
      server: ''
      username: ''
  webhooks: []
vpn_ip: 68.235.35.124:47430
